config/routes.rb
Richard::Application.routes.draw do
  
   root :to => "pages#home"
    match '/contact', :to => 'pages#contact'
     match '/project',   :to => 'pages#project'
     match '/resume',    :to => 'pages#resume'
     match '/home',  :to => 'pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def project
    @title = "Projects"
  end

  def resume
    @title = "Resume"
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>
  
	
		
			<div class="richardnav">
		          
		          <ul class="pills">
		           		
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Projects", project_path %></li>
				 	<li><%= link_to "Resume", resume_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
				
		          </ul>
		
	
	</div>
	
     
		<%= audio_tag("yiruma.ogg", :autoplay => true) %>
		
      
	</div>
	

	 

</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %> <![endif]-->
<%= stylesheet_link_tag 'bootstrap' , :media => 'screen' %>

app/views/layouts/application.html.erb
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Richard Lung | <%= @title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets'%>
	
	</head>
	<body>
	

	
		<%= render 'layouts/header' %>
		<div class = "container">
	
				<%= yield %>
				</section>
	    	
		<%= debug(params) if Rails.env.development? %>
	   
			</div>
			<div class="ifoot">&copy; Richard Lung 2011</div>
	</body>
</html>

app/views/pages/contact.html.erb
<script type="text/javascript" src="http://form.jotform.com/jsform/12883206315"></script>

app/views/pages/home.html.erb
<div class="about">
	<h2>About me</h2>
	<hr><hr>
Hello World! 
<br>My name is Richard. I'm 4th year computer science student at UCLA.
<br>I love programming! currently I'm doing Ruby on Rails and Android.
<br>if you have any suggestion about interesting project, please let me know
<br>I have done several projects, if interested you can check it out <%= link_to "here", project_path %>
<br>I love Google, because it help me so much!
<br>I also love to eat. so if you have any suggestion where to eat please let me know.
<br>I love music, I play guitar during my free time. 
<br>Thank you for checking out my web. Forgive my crappy design :)

<br><br>
Regards,<br>
Richard
<br><br>
<h2>Favorite Quotes</h2>
<hr><hr>
<i>"Stay hungry, stay foolish."</i> - Steve Jobs<br>
<i>"If I fail, I try again, and again, and again"</i> - Nick Vujicic   |   check his inspirational <%= link_to "video", "http://www.youtube.com/watch?v=wOlTdkYXuzE" %>
</div>

<br>
<br>
<br>
<font size="1">*) Music credit to Yiruma</font>

app/views/pages/project.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <h1>My Projects</h1>

      <!-- Example row of columns -->
      <div class="row">
        
        <div class="span6">
          <h2>Software Programming</h2>
          <ul>
			<li>Remove duplicate files <a href="files/remdup">Download</a><br>Removing duplicate files in the directory and subdirectory where the program is executed. <br>Written in C</li>
			<li>Simple-paint  <a href="files/Simple-Paint.zip">Download</a> <br>Simplified version of paint. Written in Java</li>
			
			<li>Koch snowflake curve   <a href="files/KochCurve.java">Download</a><br>Koch snowflake graphics animation with GUI. <br>Written in Java</li>
			<li>Query Tree <a href="files/Query-Tree.zip">Download</a><br>Simple AI. Guessing user's mind based on database stored by the previous user. Written in Java</li>
			<li>Multithread <a href="files/multithreading.zip">Download</a><br>Modifying simple ray tracer code by Brian Allen so that the code is multithreaded and runs several times faster on multicore machine. Written in C</li>
			
			</ul>
       </div>

		<div class="span5">
          <h2>Web Development</h2>
         <ul><li><a href="http://indobruin.com">www.indobruin.com</a><br>Indonesian Community in UCLA's Web!'</li></ul>
 
        </div>
        <div class="span6">
          <h2>Ongoing Project</h2>
          <ul>
			<li>Please <%= link_to "contact", contact_path %> me for more details!</li>
		
		  </ul>
        </div>
	

      </div>

     

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/resume.html.erb
<div class="resume">
<a href='/files/LungRichard_ComputerScience.pdf'>Download PDF</a><br>
</div>

<object width="595" height="430">
  <param name="MOVIE" value="solid2.swf">
  <param name="PLAY" value="true">
  <param name="LOOP" value="true">
  <param name="QUALITY" value="high">
  <embed src="/files/LungRichard_ComputerScience.swf" width="595" height="430"
   play="true" align="" loop="true" quality="high"
   TYPE="application/x-shockwave-flash"
   PLUGINSPAGE="[[http://www.macromedia.com/go/getflashplaye]r]">
  </embed>
</object>